export interface User {
  id: string;
  name: string;
  avatar: string;
}

export interface Reaction {
  emoji: string;
  count: number;
  users: string[]; // User IDs
}

export interface Post {
  id: string;
  userId: string;
  userName: string;
  userAvatar: string;
  imageUrl: string;
  caption: string;
  timestamp: Date;
  location?: string;
  reactions: Reaction[];
  aiVibeTags: string[]; // Generated by Gemini
  authenticityScore: number; // 1-100, Generated by Gemini
}

export interface Vault {
  id: string;
  name: string;
  description: string;
  members: User[];
  coverImage: string;
  posts: Post[];
  lastActive: Date;
}

export type ViewState = 'HOME' | 'VAULT_DETAIL' | 'CREATE_POST' | 'SCRAPBOOK' | 'PROFILE';

export interface VibeAnalysisResult {
  tags: string[];
  authenticityScore: number;
  vibeDescription: string;
}

export interface ScrapbookStory {
  title: string;
  narrative: string;
  mood: string;
}